### ISSUE TITLE
Performance question

### ISSUE THREAD

**Issue by LucaNicosia** [alex-petrenko/faster-fifo#38]
Hi team,
I need to use a queue to make N producers communicate with M consumers (N > M). Today I'm using async queue, but it doesn't scale well, so I want to upgrade to multiprocessing.
The producers are going to write on the queue at a pretty high rate and each element of the queue can be up to 100 MB.

My question is: I saw the performance tests in the README, but it wasn't clear to me the dimension of the messages you were exchanging. Do you think that faster-fifo will still be faster than multiprocess.Queue?

I posted the question here because I didn't found any slack or discord etc. If there is one, please let me know. I can post this question there as well

**Comment by alex-petrenko** [comment]
Hi Luca!

The queue handles large messages by serializing them and writing them into shared memory. You can allocate a larger buffer in the queue constructor to make sure you have a sufficient amount of space in the buffer.

This is the standard python's queue semantics. But if you want to push the performance higher, for large messages it makes sense to write a custom serializer (pickler) such that the messages are just copied to shared memory directly without serializing the whole thing. This is what PyTorch does for shared memory tensors.

The tests in the Readme are for pretty small messages, because I wanted to highlight the message passing performance. With large messages it will depend on your serialization mechanism and how quickly you can process such large messages. My guess is that queue won't be a bottleneck since the total number of messages can't be that large if they're 100Mb each.

You can join Discord by clicking on the Discord badge on top of README.

**Comment by LucaNicosia** [comment]
Thanks @alex-petrenko! That's what I wanted to hear.
