### ISSUE TITLE
How to use most efficiently?

### ISSUE THREAD

**Issue by rsend** [alex-petrenko/faster-fifo#48]
Hi,
I'm using this implementation to speed up data transfer between two processes on a Raspberry Pi 3 Model B. However, I'm not 100% sure I'm using it most efficiently, and would appreciate any pointers to speed it up some more.

First, about size. What is the difference between max_size_bytes and maxsize, if each of my items is one character shouldn't they be the same? Can I omit the latter if I specify the former?

I seem to be incurring a lot of time processing the queue (maybe in pickling and unpickling) so I'm looking for remaining optimizations. I'm using a list / chunk size of 1000, 2000 or 5000 items at the moment (trying to see what's fastest), and I need to process a total of 7200 bytes per second,  both in and out of the queue.

Second, application wise at a high level, I have one process that continuously puts data into the queue, and a second one that only removes from it. The first part is done like this:

```while(1):
    while(hadfullexception):
      try:
        tx.put_many_nowait(newlist)
      except Full:
        print(datetime.datetime.now(),": Still full")
        hadfullexception=1
      hadfullexception=0
    if(not ser1.peek()==b''):
      ____________________________________
      newbytes = ser1.read1()
      newlist = [newbytes[i:i+1] for i in range(0, len(newbytes))]
      try:
        tx.put_many_nowait(newlist)
      except Full:
        print(datetime.datetime.now(),": TX Queue full")
        time.sleep(0.00001)
        hadfullexception=1
        continue
        ______________________________________
    time.sleep(0.0001)
```
My understanding is that using put_many is an efficient use of locks. However - if the queue is not full but the newlist is larger than the available space, what happens?

On the other side, it is even simpler:
```while(1):
    time.sleep(0.000001)
    try:
      rxbytes=rx.get_many_nowait()
    except Empty:
      continue
```

Same idea. Is this reasonably efficient, or can I do better?

Here is a screenshot of profiling between the two horizontal lines above. As you can see, time is mostly spent in reduction. Can I do better maybe with different datatypes here, or a different serializer?

EDIT: I read up on pickle protocol 5 which supports out-of-band memory. However, I don't feel like I'm knowledgeable enough to use that without further guidance, which may be out of scope of this particular question :/

![grafik](https://github.com/alex-petrenko/faster-fifo/assets/2659987/0d14ebfd-e3b3-462b-b1f0-409c33be3621)

Thanks,
R

**Comment by alex-petrenko** [comment]
My guess would be that your actual interaction with the queue takes negligible amount of time, and most of the time the CPU is busy pickling.

In this situation, the first thing to consider is whether you can use shared memory between processes to avoid serializing and deserializing data entirely.
One option is to have a pre-allocated fixed size shared array where you put the data that needs to be sent to the other process. Then you can just send a tiny message (offset, size) to the other process instead of sending the whole object.

This is a bit of a hassle to setup but should not be too hard. In your specific case though it seems like you're sending through raw binary data (?), in which case you can just define a custom noop pickler.
README mentions this: ```q = Queue(max_size_bytes=100000, loads=custom_deserializer, dumps=custom_serializer)```

We also have a test for this: https://github.com/alex-petrenko/faster-fifo/blob/691ee7e7424ab59f6d535ddf6f4e1ffeadac2fd7/cpp_faster_fifo/tests/test_faster_fifo.py#L370

LMK if this helps!

**Comment by rsend** [comment]
Hi,
Thanks for the suggestion. 

Instead of shared memory, I quickly tried the msgspec serializers earlier: https://jcristharif.com/msgspec/index.html , and got a significant speed boost in the overall application (10-20% maybe, I won't have a chance to look closely today). I THINK that's good enough for now, but I'll study it a bit more later.

My other question about the queue size still stands, though. Do you have any comment on that? I'm still not clear if / how specifying the size of that sufficiently affects how much data is serialized every time.

**Comment by alex-petrenko** [comment]
I don't think it affects how much data is being serialized.
We need to know the size of the binary message (after serialization) to determine whether it fits. So we perform serialization first and then reject messages that exceeded the limit.

It might lead to objects being serialized multiple times if you hit Queue.FULL condition frequently. Perhaps there's a further possible optimization possible for this use case. I bet this can be achieved with a custom caching serializer?

**Comment by rsend** [comment]
Well, thus far I just increased max_size_bytes until I stopped getting full exceptions. On that note, if I have (enough) RAM, can I leave both fields unspecified? I assume that the queue would just grow as needed and never hit a full exception in that case, yes?

**Comment by alex-petrenko** [comment]
No, the buffer won't grow. It's an intentional performance-motivated design choice.

I also think it's easier to manage messages that don't fit into the fixed-sized queue on the producer side instead of uncontrollably growing the shared memory buffer. Queue's memory buffer can't grow indefinitely anyway, so you'd have to deal with handling FULL exceptions regardless.

Default buffer size is `DEFAULT_CIRCULAR_BUFFER_SIZE = 1000 * 1000  # 1 Mb`. If RAM is not an issue, then bumping it by 10-100x should help with performance

**Comment by rsend** [comment]
The producer won't add too much to the queue if there isn't also a consumer running, there is some flow control with timeouts. However, if the data transfer is extremely one-directional, then the consumer can't empty the queue fast enough and it will grow until the direction of transfer balances but this is not the normal use case. This is why the queue size needs to be bigger, so I'll try some larger multiple (as I have it now, to avoid full exceptions). I was just wondering if keeping the size overhead small relative to my messages would give me some serialization speed benefits. Thanks for the explanations!
